"""Attribution and third-party terms emitted alongside built decks.

Legal text for deck *content* lives here, not in the repository LICENSE. The
repository ships only the MIT-licensed build pipeline; a generated deck bundles
third-party content whose terms are reproduced here and written into every
release. Each source is marked used / not used based on the build manifest, so
the notice cannot drift from what a deck actually contains.
"""

from __future__ import annotations

from collections.abc import Mapping

_WORDFREQ = (
    "Frequency ranking derives from the `wordfreq` dataset "
    "(https://github.com/rspeer/wordfreq), MIT-licensed, aggregating multiple "
    "corpora under their respective terms."
)

_MWLD = (
    "Definitions, example sentences, pronunciation (IPA), and headword audio are "
    "retrieved from the Merriam-Webster Learner's Dictionary API and are "
    "© Merriam-Webster, Incorporated. This content is NOT placed under an open "
    "license. Reuse or redistribution must comply with the Merriam-Webster "
    "Dictionary API Terms of Service "
    "(https://dictionaryapi.com/info/terms-of-service) and Brand Guidelines "
    "(https://dictionaryapi.com/info/branding-guidelines). No endorsement by "
    "Merriam-Webster is implied."
)

_WIKTIONARY = (
    "Text and structured data derived from English Wiktionary via Kaikki.org are "
    "licensed CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/). "
    "Attribution is owed to English Wiktionary contributors and Kaikki.org; "
    "redistribution must stay under CC BY-SA 4.0 and indicate changes made."
)

_MEDIA = (
    "Audio files retain the license stated on their source page. Merriam-Webster "
    "audio follows the Merriam-Webster terms above; Wiktionary / Wikimedia "
    "Commons audio carries per-file licenses recorded in manifest.json."
)


def _active(manifest: Mapping[str, object], key: str) -> bool:
    try:
        return int(manifest.get(key, 0) or 0) > 0  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return False


def _mark(used: bool) -> str:
    return "used in this build" if used else "not used in this build"


def build_attribution(manifest: Mapping[str, object]) -> str:
    """Return the Markdown ATTRIBUTION document for a built release."""

    mwld_used = _active(manifest, "fetched_count")
    wiktionary_used = _active(manifest, "wiktionary_count")
    audio_used = _active(manifest, "audio_count") or _active(
        manifest, "audio_url_count"
    )

    return "\n".join(
        [
            "# Attribution and third-party terms",
            "",
            "This deck is generated by the ankglish build pipeline. The pipeline",
            "code is MIT-licensed; the deck bundles the third-party content below",
            "under the terms shown. See manifest.json for per-record provenance.",
            "",
            f"## Frequency data — wordfreq ({_mark(True)})",
            "",
            _WORDFREQ,
            "",
            f"## Dictionary — Merriam-Webster Learner's Dictionary ({_mark(mwld_used)})",
            "",
            _MWLD,
            "",
            f"## Dictionary fallback — English Wiktionary via Kaikki.org ({_mark(wiktionary_used)})",
            "",
            _WIKTIONARY,
            "",
            f"## Audio ({_mark(audio_used)})",
            "",
            _MEDIA,
            "",
            "## No warranty",
            "",
            "Provided as-is, without warranty of any kind, to the fullest extent",
            "permitted by law.",
            "",
        ]
    )


def deck_description(manifest: Mapping[str, object]) -> str:
    """Return the short sources blurb stored inside the .apkg deck."""

    sources = ["wordfreq (frequency)"]
    if _active(manifest, "fetched_count"):
        sources.append("Merriam-Webster Learner's Dictionary © Merriam-Webster")
    if _active(manifest, "wiktionary_count"):
        sources.append("English Wiktionary / Kaikki.org (CC BY-SA 4.0)")
    return (
        "Sources: "
        + "; ".join(sources)
        + ". Merriam-Webster content is not openly licensed — see the release "
        "ATTRIBUTION.md and dictionaryapi.com terms. Pipeline code: MIT."
    )
